###
# Get all transactions
GET {{url}}/transactions

###
# Add transaction
POST {{url}}/transactions
Content-Type: application/json

{
    "amount": 50000,
    "targetId": "1",
    "type": "IN",
    "name": "Megtakarítás",
    "labels": ["Utalás", "Másik"]
}

###
# Get all accounts
GET {{url}}/accounts
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjQ5OTY1MTY0fQ.2hcoIg1NJtVmEC9hSVogk4-9rTXYjv8aUiZpmkcX6kw

###
# Login
POST {{url}}/users/login
Content-Type: application/json

{
    "username": "user",
    "password": "user"
}

###
