###
# Get all transactions
GET {{url}}/transactions

###
# Add transaction
POST {{url}}/transactions
Content-Type: application/json

{
    "amount": 50000,
    "targetId": "1",
    "type": "IN",
    "name": "Megtakarítás",
    "labels": ["Utalás", "Másik"]
}

###
# Get all accounts
GET {{url}}/accounts

###
